<?php

return array(

    "clear"                     => "Löschen",
    "begin"                     => "Begin",
    "documentation"             => "Dokumentation",
    "forums"                    => "Foren",
    "good"                      => "Gut",
    "bad"                       => "Schlecht",
    "expire"                    => "Enden",
    "send"                      => "Senden",
    "cancel"                    => "Abrechen",
    "start"                     => "Start",
    "dismiss"                   => "Verwerfen",
    "next"                      => "Weiter",
    "back"                      => "Zurück",
    "custom"                    => "Benutzerdefiniert",
    "url"                       => "URL",
    "last_run"                  => "Letzte Ausführung",
    "unknown"                   => "Unbekannt",
    "optional"                  => "optional",
    "received"                  => "Erhalten",
    "unanswered"                => "Unbeantwortet",
    "in_queue"                  => "In Warteschlange",
    "open"                      => "Offen",
    "pending"                   => "Wartend",
    "continue"                  => "Fortfahren",
    "retry"                     => "Wiederholen",
    "submit"                    => "Senden|Gesendet",
    "add"                       => "Hinzufügen",
    "delete"                    => "Löschen",
    "edit"                      => "Bearbeiten",
    "save"                      => "Speichern",
    "update"                    => "Aktualisieren",
    "yes"                       => "Ja",
    "no"                        => "Nein",
    "name"                      => "Name",
    "description"               => "Beschreibung",
    "public"                    => "Öffentlich",
    "date"                      => "Datum",
    "time"                      => "Uhrzeit",
    "id"                        => "ID",
    "log"                       => "Log",
    "event"                     => "Ereignis",
    "filter"                    => "Filter",
    "ip_address"                => "IP-Addresse",
    "ip"                        => "IP",
    "permanent"                 => "Dauerhaft",
    "reason"                    => "Grund",
    "colour"                    => "Farbe",
    "detail"                    => "Detail|Details",
    "only_enter_to_change"      => "Nur zum Ändern eingeben",
    "operator"                  => "Mitarbeiter|Mitarbeiter",
    "staff"                     => "Mitarbeiter",
    "frontend"                  => "Frontend",
    "message"                   => "Nachricht|Nachrichten",
    "post"                      => "Beitrag|Beiträge",
    "email"                     => "E-Mail",
    "account"                   => "Account|Accounts",
    "address"                   => "Addresse",
    "email_address"             => "E-Mail-Addresse",
    "type"                      => "Typ",
    "option"                    => "Option",
    "remove"                    => "Entfernen",
    "required"                  => "Erforderlich",
    "enabled"                   => "Aktiviert",
    "modified"                  => "Geändert",
    "change"                    => "Ändern",
    "no_change"                 => "Keine Änderung",
    "registered"                => "Registriert",
    "username"                  => "Benutzername",
    "password"                  => "Passwort",
    "general"                   => "Allgemein",
    "generalsetting"            => "Allgemeine Einstellungen",
    "setting"                   => "Einstellung|Einstellungen",
    "note"                      => "Notiz|Notizen",
    "show"                      => "Anzeigen",
    "hide"                      => "Ausblenden",
    "category"                  => "Kategorie|Kategorien",
    "parent"                    => "Parent",
    "none"                      => "Keine",
    "default"                   => "Voreinstellung",
    "disable"                   => "Deaktivieren",
    "home"                      => "Home",
    "navigation"                => "Navigation",
    "column"                    => "Spalte|Spalten",
    "action"                    => "Aktion|Aktionen",
    "value"                     => "Wert",
    "when"                      => "Wenn",
    "timezone"                  => "Zeitzone",
    "api"                       => "API",
    "system"                    => "System",
    "system_default"            => "Systemvoreinstellungen",
    "close"                     => "Schließen",
    "closed"                    => "Geschlossen",
    "unchanged"                 => "Unverändert",
    "ascending"                 => "Aufsteigend",
    "descending"                => "Absteigend",
    "number"                    => "Nummer",
    "order_by"                  => "sortieren nach",
    "active"                    => "Aktiv",
    "validate_auth"             => "Authentifizierung validieren",
    "end"                       => "Ende",
    "current"                   => "Aktuell",
    "loading"                   => "Lade",
    "processing"                => "Verarbeitung",
    "code"                      => "Code",
    "maintenance"               => "Wartung",
    "status"                    => "Status|Status",
    "count"                     => "Anzahl",
    "view"                      => "Aufruf|Aufrufe",
    "share_via"                 => "Teilen über",
    "print"                     => "Drucken",
    "reply"                     => "Antworten",
    "filter_results"            => "Ergebnisse filtern",
    "anyone"                    => "Jeder",
    "everyone"                  => "Jeder",
    "text"                      => "Text",
    "attachment"                => "Anhang|Anhänge",
    "add_attachment"            => "Anhang hinzufügen",
    "select_value"              => "Wert auswählen",
    "type_to_filter"            => "Zu filternder Typ",
    "enter_exact_ip"            => "Exakte IP-Addresse eintragen",
    "form"                      => "Formular",
    "support_portal"            => "HelpDesk",
    "previous_page"             => "Vorherige Seite",
    "reset"                     => "Zurücksetzen",
    "interval"                  => "Interval",
    "content"                   => "Inhalt",
    "sender"                    => "Absender",
    "content_sender"            => "Inhalt &amp; Absender",
    "permissions"               => "Berechtigungen",
    "no_permissions_found"      => "Keine Berechtigungen gefunden",
    "check_uncheck_all"         => "Alle auswählen / abwählen",
    "first"                     => "Erste",
    "second"                    => "Zweite",
    "third"                     => "Dritte",
    "forth"                     => "Vierte",
    "last"                      => "Letzte",
    "from"                      => "Von",
    "subject"                   => "Betreff",
    "preview"                   => "Vorschau",
    "is"                        => "Ist",
    "is_not"                    => "Ist nicht",
    "equals"                    => "Ist gleich",
    "contains"                  => "Enthält",
    "begins_with"               => "Fängt an mit",
    "ends_with"                 => "Endet mit",
    "before"                    => "Vorher",
    "after"                     => "Danach",
    "greater_than"              => "Größer als",
    "less_than"                 => "Kleiner als",
    "does_not_contain"          => "Enthält nicht",
    "viewing_operator"          => "Aktiver Mitarbeiter",
    "due"                       => "Fällig",
    "overdue"                   => "Überfällig",
    "hours_before_overdue"      => "Stunden bis zur Überfälligkeit",
    "add_rule"                  => "Regel hinzufügen",
    "new"                       => "Neu",
    "transfer"                  => "Übertragen",
    "view_all"                  => "Alle anzeigen",
    "manage"                    => "verwalten",
    "search"                    => "Suchen",
    "activate"                  => "Aktivieren",
    "deactivate"                => "Deaktivieren",
    "uninstall"                 => "Deinstallieren",
    "version"                   => "Version",
    "and"                       => "und",
    "by"                        => "von",
    "record"                    => "eintrag",
    "views"                     => "aufruf",
    "if_exists"                 => "falls es existiert",
    "of"                        => "im",            // Used in group e.g. Last Thursday of November
    "out_of"                    => "von",
    "to"                        => "bis",            // Used in a range e.g. 2 to 5

    // Languages
    "language"                  => "Sprache|Sprachen",
    "default_language"          => "Standardsprache",
    "language_toggle"           => "Sprachauswahl",

    // Date/Time
    "never"                     => "Niemals",
    "always"                    => "Immer",
    "minute"                    => "Min|Min",
    "hour"                      => "Stunde|Stunden",
    "custom_hours"              => "benutzerdefinierte Zeiten",
    "day"                       => "Tag|Tage",
    "month"                     => "Monat|Monate",
    "year"                      => "Jahr|Jahre",
    "ago"                       => "vorher",

    "editor"                    => "Editor",

    /*
     * 2.0.1
     */
    "download"                  => "herunterladen",
    "acknowledge"               => "zustimmen",

    /*
     * 2.0.2
     */
    "show_details"              => "Details anzeigen",
    "hide_details"              => "Details ausblenden",
    "welcome"                   => "Willkommen",

    /*
     * 2.0.3
     */
    "sort_by"                   => "Sortieren nach",
    "frequently_used"           => "Regelmäßig benutzt",
    "recently_used"             => "Kürzlich benutzt",
    "recently_created"          => "Kürzlich erstellt",
    "load_more"                 => "Weitere laden",
    "clear_selected"            => "Auswahl löschen",
    "expand_all"                => "Alle erweitern",
    "collapse_all"              => "Alle einklappen",
    "show_more"                 => "Weitere laden",
    "custom_fields"             => "benutzerdefinierte Felder",

    /*
     * 2.1.0
     */
    "recently_viewed"           => "Recently Viewed Tickets",
    "na"                        => 'N/A',
    "total"                     => "Total",
    "disabled"                  => "deaktiviert",
    "not_set"                   => "nicht gesetzt",
    "add_item"                  => "hinzufügen :item",
    "edit_item"                 => "Edit :item",
    "any"                       => "jegliche",
    "module_generalsetting"     => ":module General Settings",
    "field"                     => "Feld",
    "rule"                      => "Regel",
    "start_date"                => "Start Datum",
    "end_date"                  => "Ende Datum",
    "submitted_by"              => "gesendet von",
    "every_minutes"             => "Alle :minutes",
    "at_time"                   => "at :time",

    /*
     * 2.1.1
     */
    "or"                        => "oder",
    "size"                      => "Größe",
    "edited"                    => "editiert",
    "scheduled_for"             => "Geplant für",
    "drag_and_drop"             => "Anhänge hierher ziehn.",

    /*
     * 2.1.2
     */
    "just_now"                  => "jetzt",
    "minutes_ago"               => ":number Minute zuvor|:number Minuten zuvor",
    "hours_ago"                 => ":number Stunde zuvor|:number Stunden zuvor",
    "days_ago"                  => ":number Tag zuvor|:number Tage zuvor",
    "months_ago"                => ":number month ago|:number Monate zuvor",
    "years_ago"                 => ":number Jahr zuvor|:number Jahre zuvor",
    "shortly"                   => "kürzlich",
    "in_minutes"                => "in einer Minute|in :number Minuten",
    "in_hours"                  => "in einer Stunde|in :number Stunden",
    "in_days"                   => "in einem Tag|in :number Tagen",
    "in_months"                 => "in :number month|in :number Monaten",
    "in_years"                  => "in :number year|in :number Jahre",
    "number_minutes"            => ":number Minute|:number Minuten",
    "number_hours"              => ":number Stunde|:number Stunden",
    "number_days"               => ":number Tag|:number Tage",
    "number_months"             => ":number Monat|:number Monate",
    "number_years"              => ":number Jahr|:number Jahre",
    "recipients"                => "Empfänger",
    "posted"                    => "Geschickt",
    "locked"                    => "Gesperrt",
    "draft"                     => "Entwurf",

    /*
     * 2.2.0
     */
    "monday"                    => "Montag",
    "tuesday"                   => "Dienstag",
    "wednesday"                 => "Mittwoch",
    "thursday"                  => "Donnerstag",
    "friday"                    => "Freitag",
    "saturday"                  => "Samstag",
    "sunday"                    => "Sontak",
    "inactive"                  => "Inaktiv",
    "run"                       => "läuft",

/*
     * 2.3.0
     */
    "regex"                     => "Regex Validation",
    "check_all"                 => "Wähle alle aus",
    "uncheck_all"               => "Wähle alle ab",
    "after_and_including"       => "nach und einschließlich",
    "add_link"                  => "Link hinzufügen",
    "unlink"                    => "Link entfernen",
    "link"                      => "Link",

    /*
     * 2.3.1
     */
    "clone"                     => "duplizieren",
    "created_date"              => "Erstellungsdatum",
    "alphabetical"              => "Alphabetisch",
    "random"                    => "Zufällig",
    "blocked"                   => "Blockiert",
    "private_to"                => "Privat an",
    "refresh"                   => "Aktualisieren",
    "provider"                  => "Anbieter",
    "export"                    => "Export|Exports",
    "generate"                  => "Generieren",

    /*
     * 2.4.0
     */
    "show_count_more"           => "Zeige :count mehr...",
    "manual"                    => "Manuell",
    "automatic"                 => "Automatisch",
    "hook"                      => "Hook",
    "event"                     => "Ereignis|Ereignisse",
    "test"                      => "Test",

    /*
     * 2.5.0
     */
    "domain"                    => "Domain|Domains",
    "move_to_trash"             => "verschiebe in Papierkorb",
    "trash"                     => "Papierkorb",
    "trash_desc"                => "Einträge die mehr als :number Tage im Papierkorb sind werden gelöscht.",
    "restore"                   => "Wiederherstellen",
    "delete_forever"            => "Unwiederruflich löschen",

    /*
     * 2.6.0
     */
    "remove_all"                => "entferne alle",

    /*
     * 3.0.0
     */
    "previous"                  => "vorher",
    "neutral"                   => "Neutral",
    "and"                       => "und",            // Used in "A and B"
    "optional"                  => "Optional",
    "january"                   => "Januar",
    "february"                  => "Februar",
    "march"                     => "März",
    "april"                     => "April",
    "may"                       => "Mai",
    "june"                      => "Juni",
    "july"                      => "Juli",
    "august"                    => "August",
    "september"                 => "September",
    "october"                   => "Oktober",
    "november"                  => "November",
    "december"                  => "Dezember",
    "jan"                       => "Jan",
    "feb"                       => "Feb",
    "mar"                       => "Mar",
    "apr"                       => "Apr",
    "jun"                       => "Jun",
    "jul"                       => "Jul",
    "aug"                       => "Aug",
    "sep"                       => "Sep",
    "oct"                       => "Okt",
    "nov"                       => "Nov",
    "dec"                       => "Dez",
    "mon"                       => "Mon",
    "tue"                       => "Die",
    "wed"                       => "Mit",
    "thu"                       => "Don",
    "fri"                       => "Fre",
    "sat"                       => "Sam",
    "sun"                       => "Son00",
    "ordinal_th"                => "",
    "ordinal_st"                => "",
    "ordinal_nd"                => "",
    "ordinal_rd"                => "",
    "range_separator"           => " bis ",
    "week_abbr"                 => "Wo",
    "scroll_to_increment"       => "Scroll um zu erhöhen",
    "click_to_toggle"           => "Clicken um umzuschalten",
    "am"                        => "AM",
    "pm"                        => "PM",

);
